on: push
jobs:
    container-job:
        runs-on: ubuntu-latest
        container: 
          image: node:17.6.0
          volumes:
            - code:/code

        steps:
            - run: pwd;echo;ls -lah -R /code/
            # - run: /code/terraform_net.sh
            # - run: /code/terraform.sh
            # - run: /code/ansible_1.sh