on: push
env:
  script: terraform_net.sh
jobs:
    container-job:
        runs-on: ubuntu-latest
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code

        steps:
            - run: |
                echo hello1
                echo hello2
                cat ${{env.script}}

            # - run: /code/terraform_net.sh
            # - run: /code/terraform.sh
            # - run: /code/ansible_1.sh

# write a script with 5 steps, all of which are optitional
# build a new image with script in it
# run container based job with args set to 1 of the 5
# Future works will focus on improving or/and extending the script