on: push

jobs:
    terraform-network:
        runs-on: ubuntu-latest
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code

        steps:
            - run: |
                echo installing requirements
                echo run terraform code

    terraform-infra:
        runs-on: ubuntu-latest
        needs: terraform-network
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code
        steps:
        - uses: actions/checkout@main
          with:
            path: code
        - run: |
                ls -R .  || true
                ls -R code || true
                ls -R /code || true
                echo installing requirements
                ls /workspaces/deleteme/.github/workflows/custom-container-actions.yml
                echo run terraform code
            # - run: /code/terraform_net.sh
            # - run: /code/terraform.sh
            # - run: /code/ansible_1.sh
    ansible-base:
        runs-on: ubuntu-latest
        needs: terraform-infra
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code

        steps:
            - run: |
                echo installing requirements
                echo run terraform code

    ansible-shcluster:
        runs-on: ubuntu-latest
        needs: ansible-base
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code
        steps:
            - run: |
                echo installing requirements
                echo run terraform code
    ansible-Idxcluster:
        runs-on: ubuntu-latest
        needs: ansible-base
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code
        steps:
            - run: |
                echo installing requirements
                echo run terraform code

    ansible-forwarder:
        runs-on: ubuntu-latest
        needs: ansible-base
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code
        steps:
            - run: |
                echo installing requirements
                echo run terraform code
    ansible-application:
        runs-on: ubuntu-latest
        needs: [ansible-shcluster, ansible-Idxcluster]
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code
        steps:
            - run: |
                echo installing requirements
                echo run terraform code
# write a script with 5 steps, all of which are optitional
# build a new image with script in it
# run container based job with args set to 1 of the 5
# Future works will focus on improving or/and extending the script