on: push
jobs:
    container-job:
        runs-on: ubuntu-latest
        container: 
          image: node:17.6.0
          volumes:
            - ${{local.env.GITHUB_WORKSPACE}}/code:/code

        steps:
            - run: /code/terraform_net.sh
            - run: /code/terraform.sh
            - run: /code/ansible_1.sh