on: push
jobs:
    container-job:
        runs-on: ubuntu-latest
        container: node:17.6.0
        steps:
            - run: ./terraform_net.sh
            - run: ./terraform.sh
            - run: ./ansible_1.sh