# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
vars:
  who-to-greet: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ vars.who-to-greet }}
