on: push
jobs:
    container-job:
        runs-on: ubuntu-latest
        container: 
          image: node:17.6.0
          volumes:
            - ${{github.workspace}}:/code

        steps:
            - run: pwd;echo;ls -lah -R /__w/_temp
            # - run: /code/terraform_net.sh
            # - run: /code/terraform.sh
            # - run: /code/ansible_1.sh